export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_CREATE_ACCOUNT_SUCCESS = 'USER_CREATE_ACCOUNT_SUCCESS';
export const USER_CREATE_ACCOUNT_FAILURE = 'USER_CREATE_ACCOUNT_FAILURE';
export const SELECTED_GC = 'SELECTED_GC';
